### ISSUE TITLE
是我使用姿势不对吗？

### ISSUE THREAD

**Issue by tjx666** [He110te4m/vscode-circular-dependency#17]
![image](https://github.com/He110te4m/vscode-circular-dependency/assets/41773861/78e2593c-21b7-4e81-aab1-5687e55c1368)

**Comment by He110te4m** [comment]
预期行为是什么呢？

**Comment by tjx666** [comment]
这不就是循环引用吗? 你这个插件是用来检测循环引用的吧

**Comment by He110te4m** [comment]
是检测的，那你问题是啥呢？
图里面 ab 互相引用报错了，有啥问题吗？

**Comment by tjx666** [comment]
但是那个报错不是你这个插件报告的...

**Comment by He110te4m** [comment]
提供下配置跟环境信息？

**Comment by He110te4m** [comment]
缺少复现信息，暂时关闭
